//
// Copyright (c) Mario Garcia, Under the MIT License.
//
#ifndef __VIKR_FRAMEBUFFER_HPP
#define __VIKR_FRAMEBUFFER_HPP

#include <platform/vikr_types.hpp>
#include <glm/glm.hpp>

#include <list>

namespace vikr {


class Texture;


/**
  Framebuffer abstract. Used to be derived specifically for our Renderers.
  Alittle scary, Vulkan already contains a Framebuffer object for us to use.
  We will use this class to wrap it...

  OpenGL: Associates GLFramebuffer
  Vulkan: Associates VKFramebuffer
*/
class Framebuffer {
public:

  Framebuffer() { }
  Framebuffer(vuint32 width, vuint32 height);

  vvoid SetStencilDepth(vbool stencil_depth) { m_depth_and_stencil = stencil_depth; }
  /** 
    Generate the Framebuffer with this function call.
  */
  virtual vvoid Generate() = 0;  
  /**
    Get the width of our Framebuffer texture scheme.
  */
  vuint32 GetWidth() { return m_width; }
  /**
    Get the height of out Framebuffer texture scheme. 
  */
  vuint32 GetHeight() { return m_height; }
  /**
    Set the clear color of the Framebuffer. 
  */
  vvoid SetClearColor(glm::vec3 color) { m_clearcolor = color; }
  /**
    Get the clear color of the Framebuffer. 
  */
  glm::vec3 GetClearColor() { return m_clearcolor; }
  /**
    Get the Framebuffer id.
  */
  vuint32 GetId() { return m_fbo; }


protected:
  /**
    Other texture object generated by the frame buffer.
    we use "stupid" ptrs because the textures are handled by
    our ResourceManager.
  */
  std::vector<Texture *> m_textures;
  /**
    The Framebuffer object id.
  */
  vuint32 m_fbo                     = 0;
  /**
    Associated Renderbuffer object id. 
  */
  vuint32 m_rbo                     = 0;
  /**
    Get the clear color for this framebuffer.
  */
  glm::vec3 m_clearcolor            = glm::vec3(0.1f, 0.1f, 0.1f);
  vuint32 m_width                   = 0;
  vuint32 m_height                  = 0;
  vbool m_depth_and_stencil         = false;
};
} // vikr
#endif // __VIKR_FRAMEBUFFER_HPP