# Mesh

set(VIKR_MESH_SRC_DIR ${VIKR_SRC_DIR}/mesh/)
set(VIKR_MESH_INCLUDE_DIR ${VIKR_INCLUDE_DIR}/mesh/)


set(VIKR_GLOB
  ${VIKR_GLOB}
  ${VIKR_MESH_SRC_DIR}/mesh.cpp
)

set(VIKR_GLOB
  ${VIKR_GLOB}
  ${VIKR_MESH_INCLUDE_DIR}/vertex.hpp
  ${VIKR_MESH_INCLUDE_DIR}/imesh.hpp
  ${VIKR_MESH_INCLUDE_DIR}/mesh.hpp
)